esphome:
  name: controle
  friendly_name: controle

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "usZaL4pn0ElK+VgaDxSRRtV1E7xR7pgc8wkiBjGWnuU="

ota:
  - platform: esphome
    password: "88417f12d7e732af2bdb31b85d87684e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Controle Fallback Hotspot"
    password: "ZZfIuxJDPT9P"

captive_portal:

remote_transmitter:
  pin: GPIO5
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%

remote_receiver:
  pin: GPIO4
  dump: all

button:
  - platform: template
    name: Panasonic Power Button
    on_press:
      - remote_transmitter.transmit_panasonic:
          address: 0x4004
          command: 0x8140DFA2

climate:
  - platform: midea_ir
    name: "Living Room AC"